name: CI

on:
  push:
    branches: [ master ]
    tags:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} / ${{ matrix.pip-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          # - Windows
          # - macOS
        python-version:
          - 3.7
          - 3.8
          - 3.9
        pip-version:
          - latest
    env:
      PY_COLORS: 1
      TOXENV: py${{ matrix.python-version }}
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Log python version info (${{ matrix.python-version }})
      run: python --version --version
    - name: Install dependencies
      run: |
        python -m pip install -U tox virtualenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Prepare test environment
      run: tox --notest -p auto --parallel-live
    - name: Test pip ${{ matrix.pip-version }}
      run: tox
  
  pypy:
    name: ${{ matrix.os }} / ${{ matrix.python-version }} / ${{ matrix.pip-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        python-version:
          - pypy-3.7
        pip-version:
          - latest
    env:
      PY_COLORS: 1
      TOXENV: py${{ python-version }}
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Prepare test environment
        run: tox --notest -p auto --parallel-live
      - name: Test pip ${{ matrix.pip-version }}
        run: tox
